site_name: Modelagem de Processos Curatoriais com BPMN
logo: "img/nocs.png"  # Caminho da primeira logo
theme:
  name: 'material'
  language: 'pt'
  features:
    - navigation.expand
    - navigation.tabs
    - navigation.prune
    - navigation.sections
    - search.highlight
    - search.share
    - toc.integrate
    - content.code.copy

extra_css:
  - css/custom.css

plugins:
  - search
  # - mermaid2
  - awesome-pages

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:  
  - Principal: index.md

      